# Generated by Django 3.2 on 2021-05-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=120, unique=True)),
                ('bill_date', models.DateField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField()),
                ('bill_total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.FloatField()),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productprice')),
            ],
        ),
    ]
